# suppress inspection "AlphaUnsortedPropertiesFile" for whole file
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.configuration-cache=true

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
loader_version=0.19.3
# Mod Properties
mod_version=26.1.2
maven_group=net.cyberflame
archives_base_name=viewmodel
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.155.2+26.1.2
