name: Build project
on:
  push:
    branches:
      - master # run the action on your projects default branch

jobs:
  build:
    name: Build project and upload artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'liberica'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@064a97fb0b4cef86a65f09898c572382f3af10e0
      - name: Build with Gradle
        uses: gradle/gradle-build-action@7a67f395d2631536a7591586ec1412708777346f
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs
